# Generated by Django 4.2.23 on 2025-08-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zinnia", "0006_alter_category_id_alter_entry_id_alter_entry_related"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="entry",
            new_name="zinnia_entr_status_7aff0a_idx",
            old_fields=(
                "status",
                "publication_date",
                "start_publication",
                "end_publication",
            ),
        ),
        migrations.RenameIndex(
            model_name="entry",
            new_name="zinnia_entr_slug_a9173b_idx",
            old_fields=("slug", "publication_date"),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
